### PR TITLE
Dmonsewicz/add color to secondary title for expansion panel

### PR DESCRIPTION
**Pull request by dennismonsewicz**
Modifying the `ExpansionPanel` POM ERB template to render the `Typography` Component

### CODE REVIEW

**Comment by jadefish** [comment]
imo, if we're starting to pick things out of the `ExpansionPanel`'s `Typography` component, we should just bite the bullet and render the `typography` template for the expansion panel's title and secondary content.

**Comment by dennismonsewicz** [comment]
@jadefish created an issue here https://github.com/rx/presenters/issues/260

**Comment by rx** [comment]
> typography I agree with Nick on the typography. We are already using the typography component for the text and secondary text.  Rendering that template will allow color and a large selection of styling that is unavailable right now. It really is a bug in the original implementation of the expansion panel.  Note: You many need to set the default typography sizes differently in the expansion component to get similar sizing to what is being done manually.  Let me know if you need more details to get this one redone that way.

**Comment by dennismonsewicz** [comment]
@rx definitely agree the `Typography` component should be used. I'll make the necessary adjustments.

I did create issue #260 to capture reworking the typography component.

**Pull request merged**
